# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-12-25 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('path', models.CharField(max_length=128, unique=True)),
                ('is_trunk', models.BooleanField(default=False)),
                ('last_commit', models.CharField(max_length=64)),
                ('branch_commit', models.CharField(max_length=64)),
                ('branch_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('svn_revision', models.IntegerField(null=True)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('mfc_after', models.DateField(blank=True, null=True)),
                ('msg', models.TextField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='mfctracker.Branch')),
                ('merged_to', models.ManyToManyField(blank=True, related_name='merges', to='mfctracker.Branch')),
                ('mfc_with', models.ManyToManyField(blank=True, related_name='_commit_mfc_with_+', to='mfctracker.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='CommitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mfctracker.Commit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(blank=True, max_length=30)),
                ('mfc_basket', jsonfield.fields.JSONField(default=[])),
                ('do_not_merge', models.ManyToManyField(blank=True, to='mfctracker.Commit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='mfctracker.Commit'),
        ),
    ]
