# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('path', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('mfc_after', models.DateTimeField(blank=True, null=True)),
                ('msg', models.TextField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mfctracker.Branch')),
                ('mfced_commits', models.ManyToManyField(blank=True, related_name='_commit_mfced_commits_+', to='mfctracker.Commit')),
            ],
        ),
    ]
