# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-12-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models

def renumber_commits(apps, schema_editor):
    Branch = apps.get_model("mfctracker", "Branch")
    for b in Branch.objects.all():
        counter = 1
        for c in b.commits.order_by('date'):
            c.commit_counter = counter
            counter += 1
            c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commit_counter',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(renumber_commits),
    ]
