# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='mfced_commits',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='branch',
            name='mergeinfo',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='commit',
            name='merged_to',
            field=models.ManyToManyField(blank=True, related_name='merges', to='mfctracker.Branch'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='revision',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
