# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='mfctracker.Branch'),
        ),
    ]
