# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0002_auto_20161015_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='mfc_after',
            field=models.DateField(blank=True, null=True),
        ),
    ]
