# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0002_revert_name_for_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_trunk',
            field=models.BooleanField(default=False),
        ),
    ]
