# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0003_branch_is_trunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('operation', models.CharField(max_length=8)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='mfctracker.Commit')),
            ],
        ),
    ]
