# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
from django.utils.crypto import get_random_string

import django.db.models.deletion
import jsonfield.fields

def create_profiles(apps, schema_editor):
    UserProfile = apps.get_model("mfctracker", "UserProfile")
    db_alias = schema_editor.connection.alias
    for user in User.objects.all():
        profile = UserProfile(share_token=get_random_string(length=8))
        profile.user_id = user.pk
        profile.save()

def do_nothing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfctracker', '0005_commitnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(blank=True, max_length=30)),
                ('mfc_basket', jsonfield.fields.JSONField(default=[])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles, do_nothing),
    ]
