# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='mfc_with',
            field=models.ManyToManyField(blank=True, related_name='_commit_mfc_with_+', to='mfctracker.Commit'),
        ),
    ]
