# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfctracker', '0007_commit_mfc_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='do_not_merge',
            field=models.ManyToManyField(blank=True, to='mfctracker.Commit'),
        ),
    ]
