---
- hosts: localhost
  connection: local
  become: true
  vars:
      ansible_python_interpreter: /usr/local/bin/python3.9
      version_base: /usr/local/mfctracker
      app_path: "{{version_base}}/latest/app"
      venv_path: "{{version_base}}/latest/venv"
  tasks:
    - name: install packages
      pkgng: name={{item}} state=present
      with_items:
        - postgresql13-server
        - nginx
        - uwsgi-py39
        - git-lite
        - py39-virtualenv
        - py39-supervisor
        - py39-psycopg2

    - name: enable services
      service:
        name: "{{item}}"
        enabled: true
      with_items:
        - postgresql
        - nginx
        - supervisord

    - name: Initilize database
      command: /usr/local/etc/rc.d/postgresql initdb
               creates=/var/db/postgres/data13/postgresql.conf

    - name: Start database
      service:
        name: postgresql
        state: started

    - name: Create databases
      postgresql_db: name='mfctracker'
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     template='template0'
                     login_user=postgres

    - name: Create DB user
      postgresql_user: name=mfctracker
                       password=mfctracker
                       state=present
                       login_user=postgres
                       db=mfctracker
                       priv=ALL
                       role_attr_flags=CREATEDB

    - name: create user
      user:
        name: mfctracker
        comment: "mfctracker user"

    - name: create version base directory
      file: path="{{version_base}}"
            state=directory
            mode=0755
            owner=mfctracker
            group=mfctracker

    - name: create directory for cross-version files
      file: path="{{version_base}}/html"
            state=directory
            mode=0755
            owner=mfctracker
            group=mfctracker

    - name: configure nginx
      template:
        src: "templates/nginx.conf"
        dest: "/usr/local/etc/nginx/nginx.conf"


    - name: configure supervisor
      template:
        src: "templates/supervisord.conf"
        dest: "/usr/local/etc/supervisord.conf"

    - name: copy manage.py wrapper config
      become: true
      copy:
        src: files/mfctracker-manage
        dest: /usr/local/bin/mfctracker-manage

    - name: copy sample mfctracker.env
      become: true
      copy:
        src: files/mfctracker.env
        dest: /usr/local/etc/mfctracker.env
        owner: mfctracker
        group: mfctracker

    - name: fix permissions for manage.py wrapper
      file: path=/usr/local/bin/mfctracker-manage
            mode=0755

    - name: Start nginx
      service:
        name: nginx
        state: started
